version: '3.2'

services:
  resurface:
    image: docker.resurface.io/release/resurface:3.0.30
    container_name: resurface-azure
    ports:
      - '7700:7700'
      - '7701:7701'

  azure-eh:
    image: resurfaceio-eventhub-consumer
    container_name: azure-eh-listener
    env_file:
      - .env
    volumes:
      - ${HOME}/.m2:/root/.m2
