version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:3.1.30
    container_name: resurface
    ports:
      - '7700:7700'
      - '7701:7701'

  azure-eh:
    image: resurfaceio/azure-eh-listener:1.0.0
    container_name: azure-eh-listener
    env_file:
      - .env
    volumes:
      - ${HOME}/.m2:/root/.m2
