version: '3.2'

services:
  resurface:
    image: resurfaceio/pilot:2.2.8
    container_name: azure_eh_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  azure-eh:
    image: test-azure-eh
    container_name: azure-eh
    env_file:
      - .env
    volumes:
      - ${HOME}/.m2:/root/.m2