version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:3.1.35
    container_name: resurface
    ports:
      - '7700:7700'
      - '7701:7701'

  azure-eh:
    image: azure-eh-consumer:1.0.1
    container_name: azure-eh
    env_file:
      - .env
    volumes:
      - ${HOME}/.m2:/root/.m2
