version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:2.3.1
    container_name: resurface-azure
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  azure-eh:
    image: azure-eh
    container_name: listener-azure-eh
    env_file:
      - .env
    volumes:
      - ${HOME}/.m2:/root/.m2
